# Generated by Django 5.1.4 on 2024-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
